콜백함수는 순차적인 함수의 실행을 하다보면 결국 콜백지옥을 만들게 된다. 그리고 모든 제어 흐름이 순차적이지 않고, 오류를 발생시키기 쉽다(이부분은 왜그럴까?)
그래서 promise라는 개념이 등장했다.
promise는 상태를 전달하는 객체이다. 또한 제어 흐름의 순차실행을 구현하기 위해 쉽게 연결할 수 있다.

promise는 비동기 작업의 최종적인 결과를 담고 있는 객체이다. 완료 되지 않았을떄 pending, 완료되었을때를 fulfilled, 에러와 함께 종료되었을때를 rejected라고 한다.
먼저 callback을 어떻게 promise로 바꿀 수 있는지, promise의 결과값(fulfilled)또는 에러의 원인(rejected)를 어떻게 받을 수 있는지 알아보겠다.
```
function sth1(a, callback) {
  setTimeout(() => {
    if (a === 1) {
      callback(null, a);
    } else {
      callback(new Error());
    }
  }, 1000);
}

sth1(1, (err, result) => {
  if (err) {
    console.log(err);
  } else {
    console.log(result);
  }
});
```
sth은 a가 1이면 1을 보여주고, 1이 아니면 error를 보여준다.
이것을 프로미스로 바꾸면 아래와 같다.
```
function sth2(a) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (a === 1) {
        resolve(a)
      } else {
        reject(new Error())
      }
    }, 1000);
  }
    
  );
}
console.log(sth2(1))
sth2(1).then(data => console.log(data), error => console.log(error))
sth2(2).then(data => console.log(data), error => console.log(error))
```
>>> Promise { <pending> }
>>> 1
>>> Error

Promise를 위와같이 만들수 잇으며, fulfilled 되었을때 전달해줄 값을 resolve로, rejected 되었을때 값을 reject로 전달해 주어야한다.
Promise가 전달한 값을 필요할때 사용하고 싶으면 then을 이용해서 첫번째인자는 resolve된 값을, 두번째인자는 reject한 값을 callback을 사용해 받을 수 있다.

(nodejs의 콜백기반 함수들은 3가지 특징을 가지고 있는데, 이를 활용하면 promise함수를 만드는데 유용하다. 1. 콜백은 함수의 마지막인자이며, 2. 에러는 콜백에 첫번째 인자로 전달된다 3. 모든반환값은 콜백함수의 error인자 다음으로 전달된다. 이런 특성덕분에 node의 코어모듈의 util은 promisify를 이용해 비동기콜백함수를 프로미스화(프로미스를 반환하는)할 수 있다.)